unzer_admin_config:
    path: /unzer/configuration/{all?}
    defaults:
        _controller: SyliusUnzerPlugin\Controller\ConfigurationController::configAction
        all: ''
    requirements:
        all: ".*"

unzer_admin_enable:
    path: /unzer/enable-payment-method
    defaults:
        _controller: SyliusUnzerPlugin\Controller\ConfigurationController::enableAction

unzer_admin_connection:
    path: /unzer/api/connection
    defaults:
        _controller: SyliusUnzerPlugin\Controller\ConnectionController::connectAction
