parameters:
    env(UNZER_ENCRYPTION_KEY): 'def000002f45b81aa090e24a233d11e5b6348131bf27a28fdcae1972841dd98a565d678b144a13b880c88bbea36327126f9962a40b2e07d5258360ec44c30804fb011883'
sylius_grid:
    templates:
        action:
            enable_unzer: "@SyliusUnzerPlugin/PaymentMethod/Grid/Action/create.html.twig"
    grids:
        sylius_admin_payment_method:
            actions:
                main:
                    enable_unzer:
                        type: enable_unzer
sylius_payment:
    resources:
        payment_method:
            classes:
                controller: SyliusUnzerPlugin\Controller\PaymentMethodController

sylius_ui:
    events:
        sylius.admin.order.show.content:
            blocks:
                aaa:
                    template: '@SyliusUnzerPlugin/Order/Show/_order.html.twig'
        sylius.shop.layout.stylesheets:
            blocks:
                unzer_styles:
                    template: "@SyliusUnzerPlugin/Checkout/unzer_styles.html.twig"
        sylius.shop.layout.javascripts:
            blocks:
                unzer_sripts:
                    template: "@SyliusUnzerPlugin/Checkout/unzer_scripts.html.twig"
        sylius.shop.checkout.complete.before_navigation:
            blocks:
                unzer_payment_page_dialog:
                    template: "@SyliusUnzerPlugin/Checkout/Complete/paymet_page_dialog.html.twig"
