unzer_test:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusUnzerPlugin\Controller\GreetingController::dynamicallyGreetAction  

unzer_shop:
    resource: "shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

unzer_webhook:
    path: /webhook
    defaults:
        _controller: SyliusUnzerPlugin\Controller\Front\WebhookController::webhookAction  
