unzer_test:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusUnzerPlugin\Controller\GreetingController::dynamicallyGreetAction  

unzer_shop:
    resource: "shop_routing.yaml"

unzer_webhook:
    path: /webhook
    defaults:
        _controller: SyliusUnzerPlugin\Controller\Front\WebhookController::webhookAction  
